---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provenance-linker-config
  namespace: provenance-system
  labels:
    app.kubernetes.io/name: provenance-graph-sbom-linker
    app.kubernetes.io/component: config
data:
  config.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
      
    database:
      neo4j:
        uri: "bolt://neo4j:7687"
        database: "provenance"
        max_connections: 50
        timeout: 30s
        
    cache:
      redis:
        addr: "redis:6379"
        password: ""
        db: 0
        pool_size: 10
        
    observability:
      metrics:
        enabled: true
        port: 9090
        path: "/metrics"
      tracing:
        enabled: true
        endpoint: "http://lang-observatory:4317"
        service_name: "provenance-linker"
      logging:
        level: "info"
        format: "json"
        
    security:
      cors:
        allowed_origins: ["*"]
        allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allowed_headers: ["*"]
      rate_limiting:
        enabled: true
        requests_per_minute: 100
      authentication:
        enabled: true
        jwt_secret_env: "JWT_SECRET"
        
    sbom:
      formats: ["cyclonedx", "spdx"]
      max_size: "10MB"
      validation: true
      
    signature:
      cosign:
        enabled: true
      gpg:
        enabled: true
        keyring_path: "/etc/gnupg"
        
    compliance:
      frameworks: ["nist-ssdf", "eu-cra"]
      auto_generate_reports: true
      
  logging.yaml: |
    version: 1
    disable_existing_loggers: false
    formatters:
      json:
        format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: json
        filename: /var/log/provenance-linker/app.log
        maxBytes: 10485760
        backupCount: 5
    loggers:
      provenance-linker:
        level: INFO
        handlers: [console, file]
        propagate: false
    root:
      level: INFO
      handlers: [console]