---
apiVersion: v1
kind: Namespace
metadata:
  name: provenance-system
  labels:
    name: provenance-system
    app.kubernetes.io/name: provenance-graph-sbom-linker
    app.kubernetes.io/component: namespace
  annotations:
    kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: LimitRange
metadata:
  name: provenance-system-limits
  namespace: provenance-system
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: provenance-system-quota
  namespace: provenance-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"